Task.79625
awesome-academy/natiei2024-batch-1-website-for-booking-tickets-and-managing-cinemas pull request #19
Opened 2024-08-13 03:49 UTC by thuha25

<img width="835" alt="image" src="https://github.com/user-attachments/assets/b875b682-3b70-42d6-a518-5b40d3b912b8">
https://edu-redmine.sun-asterisk.vn/issues/79625

2024-08-14 00:53 UTC, JITMinh37 approved these changes

2024-08-14 07:24 UTC, ducchung0002 approved these changes

2024-08-14 09:05 UTC, LongTCH requested changes

2024-08-14 09:05 UTC, LongTCH commented on src/main/webapp/WEB-INF/configs/spring-security.xml
> +    <security:intercept-url pattern="/popcornDrinks" access="hasRole('ROLE_CUSTOMER')"/>
/foods/**

2024-08-14 09:05 UTC, LongTCH commented on src/main/webapp/assets/user/css/popcornDrinks.css
> +.booking-progress {
food.css

2024-08-14 09:05 UTC, LongTCH commented on src/main/java/cinemas/controllers/DatVeController.java
> +    public String getDatVeCombo() {return "user/popcornDrinks";}
đưa vô ShowtimesController

2024-08-14 15:55 UTC, LongTCH approved these changes

2024-08-15 00:14 UTC, thucvijul07 approved these changes

2024-08-16 01:23 UTC, vanvtt-0952 commented on src/main/java/cinemas/controllers/user/TicketBookingsController.java
> +    @PostMapping("/showtimes/{id}") // view food of a showtime ofter selecting seats
nếu là show food sau khi chọn chỗ ngồi thì id ni là của seat nhỉ? thế thì nó nên nằm trong controller seats chứ nhỉ chứ sao lại showtime

2024-08-16 03:10 UTC, thuha25 commented on src/main/java/cinemas/controllers/user/TicketBookingsController.java
> +    @PostMapping("/showtimes/{id}") // view food of a showtime ofter selecting seats
dạ nó nằm ở controller TicketBoookingsController dùng cho việc đặt vé chứ k phải Showtime chị.
với list ghế nên id là array chị

2024-08-16 06:30 UTC, merged